### ISSUE TITLE
Readme states TensorBoard running from port 6006, but isn't

### ISSUE THREAD

**Issue by jk** [hillyu/keras-gpu#1]
The 2 year old readme states that TensorBoard is running from port 6006, but it isn't and the `Dockerfile` looks like that TensorBoard isn't even started. You might edit your `README.md`.

**Comment by hillyu** [comment]
Thanks for your feedback, updated accordingly. 
The base itself has gone through dramatic changes over the years. You may consider use google's official image as this one may not be updated to 2.x in the future.
